[package]
name = "sspvo-rs"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1

[dependencies]
yaserde = "0.8"
yaserde_derive = "0.8"
validator = { version = "0.15", features = ["derive"] }

#base64 = "0.13"
